// AuthKit Authentication Configuration
// This file is generated by the setup script
// Run `npm run setup` to reconfigure

export const AUTH_CONFIG = {
  emailPasswordEnabled: true,
  googleOAuthEnabled: true,
  setupChoice: 'both',
  generatedAt: new Date().toISOString()
};

export default AUTH_CONFIG;
